# Generated by Django 3.2.3 on 2022-03-16 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('bills', '0002_alter_bills_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
