# Generated by Django 3.2.3 on 2021-11-04 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aparcaderos', '0001_initial'),
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='actual_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buses_actual_a', to='aparcaderos.aparcaderos'),
        ),
    ]
